<?php require_once ('template/header.phtml'); ?>

<div class="row main">
    <div class="main-login main-center">
        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-horizontal">

            <?php if (count($view->errors) > 0 ): ?>
                <div class="alert alert-danger">
                    <?php foreach ($view->errors as $e): ?>
                        <span><?php echo $e; ?></span><br>
                    <?php endforeach; ?>
                </div>
            <?php endif ?>

            <div class="form-group">
                <label for="firstName" class="cols-sm-2 control-label">First Name</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <input type="text" class="form-control" name="firstName"
                               value="<?php echo $view->firstName; ?>" placeholder="Enter your First Name" required />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="lastName" class="cols-sm-2 control-label">Last Name</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <input type="text" class="form-control" name="lastName"
                               value="<?php echo $view->lastName; ?>" placeholder="Enter your Last Name" required />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="number" class="cols-sm-2 control-label">Phone Number</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <input type="text" class="form-control" name="number"
                               value="<?php echo $view->number; ?>" placeholder="Enter your Phone Number" required />
                    </div>
                </div>
            </div>

            <div class="form-group">
                <input type="radio" name="gender" value="male"> Male
                <input type="radio" name="gender" value="female"> Female
                <input type="radio" name="gender" value="other"> Other
            </div>

            <div class="form-group">
                <label for="email" class="cols-sm-2 control-label">UserName</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <input type="email" class="form-control" name="email"
                               value="<?php echo $view->email; ?>" placeholder="Enter your Username" required />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="password_1" class="cols-sm-2 control-label">Password</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <input type="password" class="form-control" name="password_1" placeholder="Enter Your Password" required />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="password_2" class="cols-sm-2 control-label">Password</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <input type="password" class="form-control" name="password_2" placeholder="Confirm Your Password" required />
                    </div>
                </div>
            </div>

            <div>
                <img src="images/<?php echo $view->captchaObjects[$view->num]->getPictureText()?>"
                     alt="no picture" style="border: solid; width: 250px;" />
            </div>
            <div class="input-group">
                <input type="text" class="form-control" name="word" placeholder="What does the image say" required />
            </div>


            <input type="checkbox" name="agreeToTerms" required>I accept to the <span style="text-decoration: underline">Terms and Conditions</span>
            <div class="form-group ">
                <button type="submit" class="btn btn-primary btn-lg btn-block login-button" name="register">Register</button>
            </div>
            <div class="login-register">
                <a href="../login.php">Login</a>
            </div>
        </form>
    </div>
</div>
<?php require_once ('template/footer.phtml'); ?>

<style>
    body, html{
        background-color: #d3d3d3;
        font-family: 'Oxygen', sans-serif;
    }
    .main{
        margin-top: 20px;
        padding-bottom: 20px;

    }
    input, input::-webkit-input-placeholder {
        font-size: 11px;
        padding-top: 3px;
    }

    .main-login{
        background-color: #fff;
        /* shadows and rounded borders */
        -moz-border-radius: 2px;
        -webkit-border-radius: 2px;
        border-radius: 2px;
        -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    }

    .main-center{
        margin: 0 auto;
        max-width: 330px;
        padding: 40px 40px;
    }
    .login-button{
        margin-top: 5px;
    }
    .login-register{
        font-size: 12px;
        text-align: center;
    }

</style>