<?php require_once('template/header.phtml'); ?>

<input id="address" type="text" class="form-control col-sm-6" value=<?php if (isset($view->searched)) echo $view->searched; ?> >
<button type="submit" id="submit" class="btn btn-default "> <img src="../images/search.png" alt="next" height="20" > </button>
<div id="map" style="height: 600px;"></div>

<?php require_once ('template/footer.phtml'); ?>

<script> locations = <?php echo $view->locations; ?>; </script>
<script src='../js/googleAPI.js'></script>
<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"> </script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA6tBNMQzpIzDYa1uTth5NkeVgbNo5YLsA&libraries=places&callback=initMap" type="text/javascript"></script>