    </div> <!-- For the container in heaer -->


    <div class="container">
        <div class="row">
            <div id="footer" class="col-sm-12 bg-dark" style="padding: 10px 0px">
                <span class="offset-5" style="color: white;">© 2019 Copyright</span>
            </div>
        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!--    <script src="../../css/js/bootstrap.min.js"></script>-->
<!--    <script src="../../css/js/jquery.min.js"></script>-->
<!--    <script src="../../css/js/bootstrap.bundle.min.js"></script>-->
</body>
</html>